[features]
seeds = false
skip-lint = false
[programs.localnet]
parrhesia = "7u18B2KUkivrUCegw5KEKNCNjjCYVmukeBx4Sh8rfBWC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/_amitayas_/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
